### ISSUE TITLE
Text-mask with ReactiveFormsModule, does not work.

### ISSUE THREAD

**Issue by heidermatos** [cesarrew/ng2-currency-mask#34]
I am using the directive **ng2-currency-mask**, which is working perfectly, in my form I am using validation with **ReactiveFormsModule**, in the fields that I use the **ng2-currency-mask** validation does _not work_. _I've tried it in every way without success._

Someone got it?
Do you have an example so you can tell me?

Thank you.

**Comment by heidermatos** [comment]
Any solution for working with ReactiveFormsModule?

**Comment by mbenvenuto** [comment]
same here.. can't find a way to work =/

**Comment by fmontes** [comment]
Same here.

**Comment by tobiasetter** [comment]
@heidermatos @mbenvenuto @fmontes This mask is currently not working with ReactiveFormsModule.

**Comment by heidermatos** [comment]
@tobiasetter I could not make it work with ReactiveFormsModule

**Comment by tobiasetter** [comment]
@heidermatos Exactly how I said. It does not work with ReactiveFormsModule. If you want it to work with ReactiveFormsModule, you have to change the code of ng2-currency-mask.

**Comment by cesarrew** [comment]
I'll check it out. I've been busy in these days.

**Comment by heidermatos** [comment]
@cesarrew obrigado

**Comment by heidermatos** [comment]
@tobiasetter  Did you get it to work? I am still having this pending in my project.

**Comment by cesarrew** [comment]
@heidermatos @mbenvenuto @fmontes @tobiasetter Can you provide a sample code reproducing the error?

**Comment by heidermatos** [comment]
@cesarrew no meu caso não gera erro. Acontece que ao clicar dentro do input depois clicar fora por exemplo, não é validado a obrigatoriedade do "formControlName" conforme configurei no meu formulário.

Segue o exemplo de código que utilizo:

`<input type="text" class="form-control" (blur)="atualizarValores()" formControlName="valorRecolherTaxas" id="txtValorRecolherTaxas"
           required currencyMask [options]="{ prefix: 'R$ ', thousands: '.', decimal: ',' }"/>`

**Comment by cesarrew** [comment]
@heidermatos @mbenvenuto @fmontes @tobiasetter
The new version 4.3.4 for Angular 4 should fix this issue. Please check it out.

**Comment by chimung** [comment]
@cesarrew Seem it still not work in Angular 5. Any updates ?
