### ISSUE TITLE
ion-input not working

### ISSUE THREAD

**Issue by MaickelHubner** [cesarrew/ng2-currency-mask#79]
How I use it with IONIC3 <ion-input>?

**Comment by MaickelHubner** [comment]
Work if I import in the page module, but an error occurred:

undefined is not an object (evaluating 'document.selection.createRange')

**Comment by MaickelHubner** [comment]
`<ion-item>
      <ion-label stacked>Valor</ion-label>
      <ion-input currencyMask type="tel" [(ngModel)]="movimento.valor" [disabled]="movimento.tipo == 'Rateio'" [id]="'yourInputId' + index" (focus)="scrollTo(index)"></ion-input>
    </ion-item>`

**Comment by MaickelHubner** [comment]
+1 ... in console:

(blur) is deprecated in ion-input, use (ionBlur) instead

PS: I change the (focus) in TAG to (ionFocus) too

**Comment by ferreyes** [comment]
Did you solve this??

**Comment by MaickelHubner** [comment]
I do not, @ferreyes . You would have to change the source because document.selection.createRange is deprecated. I implemented a directive to handle this formatting, but you would have to use a logic similar to:

`
  private setSelectionRange(input, selectionStart, selectionEnd) {
    if (input.setSelectionRange) {
      input.setSelectionRange(selectionStart, selectionEnd);
    } else if (input.createTextRange) {
      var range = input.createTextRange();
      range.collapse(true);
      range.moveEnd('character', selectionEnd);
      range.moveStart('character', selectionStart);
      range.select();
    }
  }

`

**Comment by cesarrew** [comment]
Could anyone confirm this issue in the latest version (5.0.1)?

**Comment by faberjr** [comment]
Can confirm it is still happening. 
Just got the latest release (5.2.0) and this is a problem. 

When using ion-input with "currencyMask" javascript logs an error: 
```
Cannot read property 'apply' of undefined
    at CurrencyMaskDirective.handleBlur (currency-mask.directive.js:45)
```
Works with a normal input.

**Comment by arturbianchi** [comment]
Same error here using Angular 5.
`<mat-form-field>
    <input matInput currencyMask>
</mat-form-field>`

**Comment by jhonycage** [comment]
Experiencing the same issue

**Comment by victordev** [comment]
Same problem with me

**Comment by kyleabens** [comment]
Any update on this?

**Comment by dacrypt** [comment]
Same issue here. Ionic4+angular6

 <ion-input currencyMask></ion-input>

Doesn't work.
